use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A single DALL-E 3 prompt generated by Claude for one condition slot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedPrompt {
    /// Condition slot identifier (c1–c4).
    pub id:              String,
    /// Human-readable condition label e.g. "Daily Use".
    pub label:           String,
    /// Scene environment e.g. "White Studio".
    pub environment:     String,
    /// Full DALL-E 3 prompt text.
    pub prompt:          String,
    /// Comma-separated terms to avoid in image generation.
    pub negative_prompt: String,
    /// Canvas preview background gradient start colour (hex).
    pub bg_from:         String,
    /// Canvas preview background gradient end colour (hex).
    pub bg_to:           String,
    /// Condition accent colour used for UI highlights (hex).
    pub accent:          String,
    /// Short mood/style keywords for display tags.
    pub mood:            Vec<String>,
}

/// A past mockup run retrieved from pgvector via cosine similarity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RagHit {
    /// Unique run identifier.
    pub id:              Uuid,
    /// Original product text used for this run.
    pub product_text:    String,
    /// Condition slot identifier.
    pub condition_id:    String,
    /// Condition label.
    pub condition_label: String,
    /// Scene environment.
    pub environment:     String,
    /// The DALL-E 3 prompt that was used.
    pub prompt_text:     String,
    /// Cosine similarity score (0.0–1.0) against the current query.
    pub similarity:      f64,
    /// GPT-4o QA score assigned to this run's output image.
    pub qa_score:        Option<f64>,
}

/// GPT-4o Vision quality assessment result for one generated image.
#[derive(Debug, Serialize, Deserialize)]
pub struct QaResult {
    /// Quality score in the range 0.0–1.0.
    pub score:    f64,
    /// Whether the image meets the platform quality threshold.
    pub passed:   bool,
    /// One-sentence assessment summary.
    pub feedback: String,
    /// Specific issues identified, if any.
    pub issues:   Vec<String>,
}

/// A fully resolved mockup — prompt + generated image + QA score.
#[derive(Debug, Serialize)]
pub struct MockupResult {
    pub condition_id:    String,
    pub condition_label: String,
    pub environment:     String,
    pub prompt:          String,
    pub image_url:       Option<String>,
    pub qa_score:        Option<f64>,
    pub qa_passed:       bool,
    /// UUID of the pgvector record created for this run.
    pub stored_id:       Option<Uuid>,
}
